const jokes: string[] = [
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't eggs tell jokes? Because they might crack up.",
    "Why was the math book sad? Because it had too many problems.",
    "I told my computer I needed a break, and now it won’t stop sending me Kit-Kats.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "I used to play piano by ear, but now I use my hands.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the chicken join a band? Because it had drumsticks.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why don't oysters donate to charity? Because they're shellfish.",
    "I'm reading a book on anti-gravity. It's impossible to put down.",
    "How does a penguin build its house? Igloos it together.",
    "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "I tried to catch some fog earlier. I mist.",
    "What do you call a pile of cats? A meow-tain.",
    "I don’t trust stairs. They’re always up to something.",
    "Why do cows wear bells? Because their horns don’t work.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why don't some couples go to the gym? Because some relationships don’t work out.",
    "I'm afraid for the calendar. Its days are numbered.",
    "What did the grape do when it got stepped on? Nothing but let out a little wine.",
    "Why do we tell actors to break a leg? Because every play has a cast.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "I couldn't figure out how to put my seatbelt on. Then it clicked.",
    "What do you call a fish with no eyes? A fsh.",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why did the computer go to the doctor? It had a virus.",
    "How do you organize a space party? You planet.",
    "I’m reading a book about anti-gravity. It’s impossible to put down.",
    "What did one hat say to the other? Stay here, I’m going on ahead.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "How does a scientist freshen her breath? With experi-mints.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised."
  ];
  
export default jokes;
  